"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useAuth = exports.YsAuthProvider = exports.logout = exports.login = exports.YsAuthAmpliftConfig = void 0;
var YsAuth_1 = require("./YsAuth");
Object.defineProperty(exports, "YsAuthAmpliftConfig", { enumerable: true, get: function () { return YsAuth_1.YsAuthAmpliftConfig; } });
Object.defineProperty(exports, "login", { enumerable: true, get: function () { return YsAuth_1.login; } });
Object.defineProperty(exports, "logout", { enumerable: true, get: function () { return YsAuth_1.logout; } });
var YsAuthProvider_1 = require("./YsAuthProvider");
Object.defineProperty(exports, "YsAuthProvider", { enumerable: true, get: function () { return YsAuthProvider_1.YsAuthProvider; } });
Object.defineProperty(exports, "useAuth", { enumerable: true, get: function () { return YsAuthProvider_1.useAuth; } });
